In [4]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr)

[1 2 3 4]


In [5]:
arr.shape

(4,)

In [6]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr2d.shape

(2, 4)

In [8]:
arr[1:3]

array([2, 3])

In [14]:
arr2d[:1, 2:3]

array([[3]])

In [7]:
arr = np.array([10,23,2,7,90,65,32,66,70])
idx = [1,3,5]

arr[idx]

array([23,  7, 65])

In [8]:
arr > 2

array([ True,  True, False,  True,  True,  True,  True,  True,  True])

np.arrage(Start이상, Stop미만)

In [10]:
arr2 = np.arange(1,11)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
arr2 = i in i np.araa

SyntaxError: invalid syntax (740826074.py, line 1)