In [6]:
import numpy as np

arr = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [7]:
arr.shape

(4,)

In [5]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr2d.shape

(2, 4)

In [8]:
arr[1:3]

array([2, 3])

In [14]:
arr2d[:1, 2:3]

array([[3]])

In [16]:
arr = np.array([10,23,2,7,90,65,32,66,70])
idx = [1,3,5]

arr[idx]

array([23,  7, 65])